# -*- coding: utf-8 -*-
"""plant village disease prediction1111.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LiqLg0E8BSvEut9bEL2guI7QnPxKGs8m
"""

# Set seeds for reproductibility
import random
random.seed(0)

import numpy as np
np.random.seed(0)

import tensorflow as tf
tf.random.set_seed(0)

"""Importing the dependencies"""

import os
import json
from zipfile import ZipFile
from PIL import Image

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers ,models

"""Image curation"""

!pip install kaggle

# Check the current working directory
import os
print(os.getcwd())

# Assuming kaggle(1).json is in the same directory as the notebook
# If not, replace "kaggle(1).json" with the full path to the file
try:
    kaggle_ceredentials = json.load(open("kaggle(1).json"))
except FileNotFoundError:
    print("Error: 'kaggle(1).json' not found. Please ensure it's in the correct directory or provide the full path.")

# Check the current working directory
import os
print(os.getcwd())

# Assuming kaggle(1).json is in the same directory as the notebook
# If not, replace "kaggle(1).json" with the full path to the file
try:
    # Replace "kaggle(1).json" with the full path to your Kaggle credentials file
    kaggle_ceredentials = json.load(open("/content/kaggle (1).json"))
except FileNotFoundError:
    print("Error: 'kaggle(1).json' not found. Please ensure it's in the correct directory or provide the full path.")

# Check the current working directory
import os
print(os.getcwd())

# Assuming kaggle(1).json is in the same directory as the notebook (/content)
try:
    # Load the Kaggle credentials from the json file
    kaggle_ceredentials = json.load(open("kaggle(1).json"))
    print("Kaggle credentials loaded successfully.")
except FileNotFoundError:
    print("Error: 'kaggle(1)(1).json' not found in /content. Please ensure it is uploaded to this directory.")
except json.JSONDecodeError:
    print("Error: Could not decode JSON from 'kaggle(1).json'. Please check the file content.")

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import os
print(os.listdir())

kaggle_ceredentials = json.load(open("kaggle.json"))

#set up API key as aenvironment variables
os.environ['KAGGLE_USERNAME'] = kaggle_ceredentials['username']
os.environ['KAGGLE_KEY'] = kaggle_ceredentials['key']

!kaggle datasets download -d abdallahalidev/plantvillage-dataset

!ls

"""Unzipping the dataset"""

with ZipFile("/content/plantvillage-dataset.zip",'r') as zip_ref:
  zip_ref.extractall()

"""Number of classes  and folder in our dataset"""

print(os.listdir("plantvillage dataset"))


print(len(os.listdir("plantvillage dataset/segmented")))
print(os.listdir("plantvillage dataset/segmented")[:5])

print(len(os.listdir("plantvillage dataset/color")))
print(os.listdir("plantvillage dataset/color")[:5])

print(len(os.listdir("plantvillage dataset/grayscale")))
print(os.listdir("plantvillage dataset/grayscale")[:5])

"""number of images in oour subfolder"""

print(len(os.listdir("plantvillage dataset/color/Grape___healthy")))
print(os.listdir("plantvillage dataset/color/Grape___healthy")[:5])

"""Data Preproccessing"""

#Dataset path
base_dir = '/content/plantvillage dataset/color'

image_path = '/content/plantvillage dataset/color/Apple___Cedar_apple_rust/025b2b9a-0ec4-4132-96ac-7f2832d0db4a___FREC_C.Rust 3655.JPG'

# Read the image
img = mpimg.imread(image_path)

print(img.shape)
# Display the image
plt.imshow(img)
plt.axis('off')  # Turn off axis numbers
plt.show()

image_path = '/content/plantvillage dataset/color/Apple___Cedar_apple_rust/025b2b9a-0ec4-4132-96ac-7f2832d0db4a___FREC_C.Rust 3655.JPG'

# Read the image
img = mpimg.imread(image_path)

print(img)

# image parameter
img_size = 224
batch_size = 32

"""Train Test Split"""

# Image Data Generators
data_gen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2  # Use 20% of data for validation
)

# Train Generator
train_generator = data_gen.flow_from_directory(
    base_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    subset='training',
    class_mode='categorical'
)

# Validation Generator
validation_generator = data_gen.flow_from_directory(
    base_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    subset='validation',
    class_mode='categorical'
)

"""Convolutional Neural Network"""

# Model Definition
model = models.Sequential()

model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(img_size, img_size, 3)))
model.add(layers.MaxPooling2D(2, 2))

model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D(2, 2))


model.add(layers.Flatten())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(train_generator.num_classes, activation='softmax'))

# model summary
model.summary()

# Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Training the Model
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples  // batch_size,  # Number of steps per epoch
    epochs=5,  # Number of epoch
    validation_data=validation_generator,
    validation_steps=validation_generator.samples
    // batch_size,  # Number of steps for validation
)

"""Model Evaluation"""

# Model Evaluation
print("Evaluating model...")
val_loss, val_accuracy = model.evaluate(validation_generator, steps=validation_generator.samples // batch_size)
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")

# Plot training & validation accuracy values
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

"""Building Predictive System"""

# Function to Load and Preprocess the Image using Pillow
def load_and_preprocess_image(image_path, target_size=(224, 224)):
    # Load the image
    img = Image.open(image_path)
    # Resize the image
    img = img.resize(target_size)
    # Convert the image to a numpy array
    img_array = np.array(img)
    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)
    # Scale the image values to [0, 1]
    img_array = img_array.astype('float32') / 255.
    return img_array

# Function to Predict the Class of an Image
def predict_image_class(model, image_path, class_indices):
    preprocessed_img = load_and_preprocess_image(image_path)
    predictions = model.predict(preprocessed_img)
    predicted_class_index = np.argmax(predictions, axis=1)[0]
    predicted_class_name = class_indices[predicted_class_index]
    return predicted_class_name

# Create a mapping from class indices to class names
class_indices = {v: k for k, v in train_generator.class_indices.items()}

class_indices

# saving the class names as json file
json.dump(class_indices, open('class_indices.json', 'w'))

# Example Usage
image_path = '/content/plantvillage dataset/00075aa8-d81a-4184-8541-b692b78d398a___FREC_Scab 3335.JPG'
image_path = '/008c85d0-a954-4127-bd26-861dc8a1e6ff___RS_HL 2431.JPG'
#image_path = '/content/test_potato_early_blight.jpg'
predicted_class_name = predict_image_class(model, image_path, class_indices)

# Output the result
print("Predicted Class Name:", predicted_class_name)

image_path = [
    '/content/005318c8-a5fa-4420-843b-23bdda7322c2___RS_NLB 3853 copy.jpg',
    '/content/0008f3d3-2f85-4973-be9a-1b520b8b59fc___JR_HL 4092.JPG'
]

for path in image_path:
    predicted_class_name = predict_image_class(model, path, class_indices)
    print(f"Predicted Class for {path}: {predicted_class_name}")

"""Plotting  image matplotlib
 Assumptions
This code assumes:

You have a working predict_image_class(model, image_path, class_indices) function.

The class_indices is the mapping from class names to class IDs .
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

def show_prediction(image_path, model, class_indices):
    # Predict the class
    predicted_class_name = predict_image_class(model, image_path, class_indices)

    # Load and show the image
    img = mpimg.imread(image_path)
    plt.imshow(img)
    plt.axis('off')
    plt.title(f'Predicted: {predicted_class_name}', fontsize=14)
    plt.show()

# Example usage
image_paths = [
     '/content/005318c8-a5fa-4420-843b-23bdda7322c2___RS_NLB 3853 copy.jpg',
    '/content/0008f3d3-2f85-4973-be9a-1b520b8b59fc___JR_HL 4092.JPG'
]

for image_path in image_paths:
    show_prediction(image_path, model, class_indices)

"""Saving the model to google drive and local disk

"""

model.save('drive/MyDrive/Youtube/trained_models/plant_disease_prediction_model.h5')

model.save('plant_disease_prediction_model.h5')